title: Crystal Yee To Ng 
position: Ph.D. Candidate
affiliation: The University of Texas at Austin
email: crystal@utexas.edu (at) example.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=887O6PoAAAAJ&hl=en
github_link: https://github.com/Crystal-ng
linkedin: https://www.linkedin.com/in/crystal-ng-01b712a0/
avatar: ./assets/img/yeeto.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
